import Head from "next/head";

import { ReactNode } from "react";
import type { NextPageWithLayout } from "@/types";

import { AdminsMain, Layout } from "@/components";

const AdminsPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Admin Management | Operation Dashboard | Diet Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AdminsMain />
      </main>
    </>
  );
};

AdminsPage.getLayout = (page: ReactNode) => {
  return <Layout>{page}</Layout>;
};

export default AdminsPage;
