import Head from "next/head";

import { ReactNode, useState } from "react";
import type { NextPageWithLayout } from "@/types";

import { PurchasesMain, Layout } from "@/components";

const PurchasesPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Purchases | Operation Dashboard | Diet Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PurchasesMain />
      </main>
    </>
  );
};

PurchasesPage.getLayout = (page: ReactNode) => {
  return <Layout>{page}</Layout>;
};

export default PurchasesPage;
