import Head from "next/head";

import { ReactNode } from "react";
import type { NextPageWithLayout } from "@/types";

import { ServiceMain, Layout } from "@/components";

const ServicePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Service Programme | Operation Dashboard | Diet Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ServiceMain />
      </main>
    </>
  );
};

ServicePage.getLayout = (page: ReactNode) => {
  return <Layout>{page}</Layout>;
};

export default ServicePage;
